examRepeat1617/Controllers/Attendances1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using examRepeat1617.Models;
using examRepeat1617.Models.Data;

namespace examRepeat1617.Controllers
{
    public class Attendances1Controller : Controller
    {
        private AttendDBContext db = new AttendDBContext();

        // GET: Attendances1
        public ActionResult Index()
        {
            var attendance = db.attendance.Include(a => a.associatedStudent).Include(a => a.associatedSubject);
            return View(attendance.ToList());
        }

        // GET: Attendances1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance attendance = db.attendance.Find(id);
            if (attendance == null)
            {
                return HttpNotFound();
            }
            return View(attendance);
        }

        // GET: Attendances1/Create
        public ActionResult Create()
        {
            ViewBag.StudentId = new SelectList(db.students, "StudentId", "FirstName");
            ViewBag.SubjectId = new SelectList(db.subjects, "SubjectId", "SubjectId");
            return View();
        }

        // POST: Attendances1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AttendanceId,AttendanceDate,Present,StudentId,SubjectId")] Attendance attendance)
        {
            if (ModelState.IsValid)
            {
                db.attendance.Add(attendance);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StudentId = new SelectList(db.students, "StudentId", "FirstName", attendance.StudentId);
            ViewBag.SubjectId = new SelectList(db.subjects, "SubjectId", "SubjectId", attendance.SubjectId);
            return View(attendance);
        }

        // GET: Attendances1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance attendance = db.attendance.Find(id);
            if (attendance == null)
            {
                return HttpNotFound();
            }
            ViewBag.StudentId = new SelectList(db.students, "StudentId", "FirstName", attendance.StudentId);
            ViewBag.SubjectId = new SelectList(db.subjects, "SubjectId", "SubjectId", attendance.SubjectId);
            return View(attendance);
        }

        // POST: Attendances1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AttendanceId,AttendanceDate,Present,StudentId,SubjectId")] Attendance attendance)
        {
            if (ModelState.IsValid)
            {
                db.Entry(attendance).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StudentId = new SelectList(db.students, "StudentId", "FirstName", attendance.StudentId);
            ViewBag.SubjectId = new SelectList(db.subjects, "SubjectId", "SubjectId", attendance.SubjectId);
            return View(attendance);
        }

        // GET: Attendances1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance attendance = db.attendance.Find(id);
            if (attendance == null)
            {
                return HttpNotFound();
            }
            return View(attendance);
        }

        // POST: Attendances1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Attendance attendance = db.attendance.Find(id);
            db.attendance.Remove(attendance);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

examRepeat1617/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li> @Html.ActionLink("Contact", "Contact", "Home") </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Roles
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Lecturers", "Index", "Lecturers")</li>
                            <li>@Html.ActionLink("Students", "Index", "Students")</li>
                            <li>@Html.ActionLink("Subjects", "Index", "Subjects")</li>
                        </ul>
                    </li>


                    @if (User.IsInRole("Lecturer"))
                    {
                        <li>@Html.ActionLink("attendace entry", "Index", "Attendances1")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>